### ISSUE TITLE
Questions about this game

### ISSUE THREAD

**Issue by independence106** [ZeroDoctor/yt-java-game#5]
Question #1: Is it possible to just use jdk to compile and run.
Question #2: I'm stuck with Tiled and unable to read the xml files, how do you do that here?
Question #3: Is it possible to do this without Maven?
Question #4: What does Maven do in this project.

I might have more questions since I'm gonna watch your utube vids and figure out how to create something similar to this. Additionally are there any libraries that can read Tiled xml files and that I can use through vs code?

Thanks!!

**Comment by ZeroDoctor** [comment]
Hello there,

1. It is possible to use jdk to compile and run. Its actually a requirement
2. Look at the [addTileMap(...)](https://github.com/ZeroDoctor/yt-java-game/blob/a034529d7852d3dbf41ba2b3a9ccda4d6debb40e/game-decay/src/main/java/com/zerulus/game/tiles/TileManager.java#L111) as a reference (I get a lot question about reading xml files so sorry about that)
3. It is possible to do this without maven but the linking the files together for compiling would be a hassle (imo). I think in one of the youtube tutorials theres a batch file that compiles everything without maven (not sure which one, its been a while).
4. So maven makes it easier to compile and run (again, imo). Simply execute: `mvn compile` to compile and `mvn exec:java` to run in the terminal

That's great! Honestly, this project has been abandon, and I can't always answer questions. However, anybody is welcome to ask or answer question. Just be aware I might not notice.

I'm sure there are libraries out there that can read xml files, but probably not through vs code (at least that I'm aware of). Maven can make loading and using libraries easier, but as long as the library is a jar file you can use the `cp`  option in `javac` to link them along with the rest of your `*.java` files. (as mention [here](https://stackoverflow.com/questions/9395207/how-to-include-jar-files-with-java-file-and-compile-in-command-prompt)). Also, if you don't like maven there is also [gradle](https://gradle.org/) which is used in many open source projects

Sorry about the delay

**Comment by independence106** [comment]
thank you!

**Comment by LunarArtemis** [comment]
I have a 4x4 Sprite character. I run the main for test anime animation is weird.
